config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index),              # 127.0.0.1:8000/board/
    path('', views.index),                      # 127.0.0.1:8000/com
    path('board/', include('board.urls')),      # 127.0.0.1:8000/board/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
    path('poll/', include('poll.urls'))
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

poll/models.py
from django.db import models

# 질문 클래스(테이블) 생성
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

# 선택 클래스 생성
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import render
from poll.models import Question
from django.http import HttpResponse


def index(request):
    question_list = Question.objects.all()
    return render(request, 'poll/index.html', {'question_list':question_list})
    # return HttpResponse("<h1>안녕~ Django!!</h1>")

def detail(request, pk):
    question = Question.objects.get(id=pk)
    return render(request, 'poll/detail.html', {'question':question})

def vote(request, pk):
    question = Question.objects.get(id=pk)
    if request.method == 'POST':
        try:
            choice = request.POST['choice']
        except:
            error = "항목을 선택하세요"
            return render(request, 'poll/detail.html', {'question':question, 'error':error})
        else:
            sel_choice = question.choice_set.get(id=choice)
            sel_choice.votes += 1
            sel_choice.save()
            return render(request, 'poll/result.html', {'question':question})
    else:
        return render(request, 'poll/detail.html', id=pk)

templates/poll/detail.html
{% extends 'base.html' %}
{% block title %}
설문 항목
{% endblock %}
{% block content %}
<div class="container my-3 card pt-3 col-4">
    <section>
        <form action="{% url 'poll:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset class="card-body">
                <legend class="card-title">{{ question.question_text }}</legend>
                {% if error %}
                <p class="error">{{ error }}</p>
                {% endif %}
                {% for choice in question.choice_set.all %}
                <p class="card-text">
                    <input type="radio" name="choice" value="{{ choice.id }}">
                    <label>{{ choice.choice_text }}</label>
                </p>
                {% endfor %}
            </fieldset>
            <p><input type="submit" class="btn btn-primary" value="투표"></p>
        </form>
    </section>
</div>
{% endblock %}

templates/poll/index.html
{% extends 'base.html' %}
{% block title %}
설문 조사
{% endblock %}
{% block content %}
    <div class="container my-3">
        <section>
            {% if question_list %}
                <div class="row">
                    {% for question in question_list %}
                    <div class="col-sm-4 my-3">
                        <div class="card text-center">
                            <div class="card-body">
                                <h5 class="card-title">{{ question.question_text }}</h5>
                                <a href="{% url 'poll:detail' question.id %}" class="btn btn-primary">투표</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
            <p>설문이 없습니다.</p>
            {% endif %}
        </section>
    </div>
</body>
</html>
{% endblock %}

templates/poll/result.html
{% extends 'base.html' %}
{% block title %}
설문 결과
{% endblock %}
{% block content %}
<div class="container my-3 card col-4">
    <section class="pt-4 pl-4">
        <h2>{{ question.question_text }}</h2>
        <ul>
            {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} -- {{ choice.votes }}votes
            </li>
            {% endfor %}
        </ul>
        <p><button type="button" class="btn btn-primary" onclick="location.href='/poll/'">설문 목록</button></p>
    </section>
</div>
{% endblock %}