common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    # LoginView 클래스 - 제네릭 뷰
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'),
         name='login'),
    # 로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원 가입
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index),              # 127.0.0.1:8000/board/
    path('', views.index),                      # 127.0.0.1:8000/com
    path('board/', include('board.urls')),      # 127.0.0.1:8000/board/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
    path('poll/', include('poll.urls'))
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ['username', 'email']

common/views.py
from django.shortcuts import render, redirect

from common.forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)       # 입력된 데이터와 폼 가져오기
        if form.is_valid():                 # 유효성 검사를 통과하면
            form.save()                     # db에 저장
            return redirect('board:index')
    else:
        form = UserForm()
    context = {'form':form}
    return render(request, 'common/signup.html', context)

templates/common/login.html
{% extends 'base.html' %}
{% block title %}
로그인 - login
{% endblock %}
{% block content %}
<div class="container my-3">
    <div class="row mb-2">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <!-- 유효성 검사 -->
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">사용자 ID</label>
            <input type="text" id="username" name="username" class="form-control"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" class="form-control"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-success">로그인</button>  <!-- input type도 상관 x -->
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block title %}
회원 가입 - signup
{% endblock %}
{% block content %}
<div class="container my-3">
    <div class="row mb-2">
        <div class="col-4">
            <h4>회원 가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인을 하세요</a></span>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <!-- 유효성 검사 -->
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">사용자 ID</label>
            <input type="text" id="username" name="username" class="form-control"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" id="password1" name="password1" class="form-control"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" id="password2" name="password2" class="form-control"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" id="email" name="email" class="form-control"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-success">회원 가입</button>  <!-- input type도 상관 x -->
    </form>
</div>
{% endblock %}