board/urls.py
from django.urls import path
from . import views

app_name = 'board'                                              # 네임 스페이스(소속)

urlpatterns = [
    # 인덱스 페이지
    path('', views.index, name='index'),                        # 127.0.0.1:8000/board/
    # 질문 목록
    path('boardlist/', views.boardlist, name='boardlist'),      # 127.0.0.1:8000/board/boardlist
    # 상세 페이지
    path('<int:question_id>/', views.detail, name='detail'),    # 127.0.0.1:8000/board/1/
    # 질문 등록 - # 127.0.0.1:8000/board/question/create/
    path('question/create/', views.question_create, name='question_create'),
    # 답변 등록 - # 127.0.0.1:8000/board/answer/create/1/
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    # LoginView 클래스 - 제네릭 뷰
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'),
         name='login'),
    # 로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원 가입
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index),              # 127.0.0.1:8000/board/
    path('', views.index),                      # 127.0.0.1:8000/com
    path('board/', include('board.urls')),      # 127.0.0.1:8000/board/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
    path('poll/', include('poll.urls'))
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'board/css/bootstrap.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <!-- 기본 표준 파일 안에 삽입될 내용 start -->
    {% block content %}
    <!-- 내용 -->
    {% endblock %}
<script src="{% static 'board/js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'board/js/bootstrap.js' %}"></script>        <!-- 순서 : jquery - bootstrap -->
{% block script %}
<!-- 자바 스크립트 소스 -->
{% endblock %}
</body>
</html>

templates/form_errors.html
<!-- 유효성 검사 -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'board:index' %}">PyWeb</a>
        <!-- 햄버거 메뉴 -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- pyweb 메뉴 -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'common:logout' %}">({{ user.username }}님)로그아웃</a>
                    {% else %}
                    <a class="nav-link active" aria-current="page" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:boardlist' %}">질문/답변</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'poll:index' %}">설문 조사</a>
                </li>
            </ul>
        </div>
    </div>
</nav>