board/urls.py
from django.urls import path
from . import views

app_name = 'board'                                              # 네임 스페이스(소속)

urlpatterns = [
    # 인덱스 페이지
    path('', views.index, name='index'),                        # 127.0.0.1:8000/board/
    # 질문 목록
    path('boardlist/', views.boardlist, name='boardlist'),      # 127.0.0.1:8000/board/boardlist
    # 상세 페이지
    path('<int:question_id>/', views.detail, name='detail'),    # 127.0.0.1:8000/board/1/
    # 질문 등록 - # 127.0.0.1:8000/board/question/create/
    path('question/create/', views.question_create, name='question_create'),
    # 답변 등록 - # 127.0.0.1:8000/board/answer/create/1/
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index),              # 127.0.0.1:8000/board/
    path('', views.index),                      # 127.0.0.1:8000/com
    path('board/', include('board.urls')),      # 127.0.0.1:8000/board/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
    path('poll/', include('poll.urls'))
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()                            # 반드시 있어야 함(NOT NULL)
    modify_date = models.DateTimeField(null=True, blank=True)       # null 허용, blank - 폼 데이터 null
    author = models.ForeignKey(User, on_delete=models.CASCADE)      # user의 username과 외래키 설정

    def __str__(self):
        return self.subject

class Answer(models.Model):
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)      # user의 username과 외래키 설정

    def __str__(self):
        return self.content

board/forms.py
from django import forms
from board.models import Question, Answer


# 질문 등록 폼
class QuestionForm(forms.ModelForm):
    class Meta:                 # 내부 클래스
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject':'제목',
            'content':'내용'
        }

# 질문 등록 폼
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content':'내용'}

board/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

def index(request):
    # 인덱스 페이지
    return render(request, 'board/index.html')

def boardlist(request):
    # 질문 목록 페이지
    # question_list = Question.objects.all()                    # db에서 전체 검색
    question_list = Question.objects.order_by('-create_date')   # 내림차순(-) / -pk도 가능
    # return HttpResponse("<h2>Hello~ Django!!</h2>")
    return render(request, 'board/question_list.html', {'question_list':question_list})

def detail(request, question_id):
    # 상세 페이지
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리(오류 대신 Page not found (404) 출력)
    # question = Question.objects.get(id=question_id)
    context = {'question':question}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    # 질문 등록
    if request.method == "POST":
        form = QuestionForm(request.POST)       # 내용이 작성된 폼
        if form.is_valid():
            question = form.save(commit=False)      # 가저장
            question.create_date = timezone.now()   # 작성일
            question.author = request.user          # 인증된 사용자(글쓴이)
            question.save()                         # 실제 저장
            return redirect('board:boardlist')          # 질문 목록 페이지 강제 이동
    else:   # request.method == "GET"
        form = QuestionForm         # 질문 등록 폼 객체 변수 생성 (비어있는 폼)
    context = {'form':form}
    return render(request, 'board/question_form.html', context)   # 공통

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리
    # question = Question.objects.get(id=question_id) # 해당 질문 1개 가져옴
    if request.method == "POST":
        form = AnswerForm(request.POST)             # 데이터가 채워진 폼
        if form.is_valid():                         # 유효성 검사
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user            # 인증된 사용자(글쓴이)
            answer.save()
            return redirect('board:detail', question_id=question_id)
    else:
        form = AnswerForm()                         # 비어있는 폼
    context = {'form':form, 'question':question}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    # 질문 수정
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)         # 새로 작성한 폼
        if form.is_valid():
            question = form.save(commit=False)                       # 가저장
            question.modify_date = timezone.now()                    # 수정일
            question.author = request.user                           # 글쓴이
            question.save()                                          # db에 저장
            return redirect('board:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)                       # 이미 작성된 폼
    context = {'form':form}
    return render(request, 'board/question_form.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    # 답변 수정
    answer = Answer.objects.get(id=answer_id)
    form = AnswerForm(request.POST, instance=answer)  # 수정할 답변 폼
    if request.method == "POST":
        answer = form.save(commit=False)
        answer.modify_date = timezone.now()
        answer.author = request.user
        answer.save()                                               # db에 저장
        return redirect('board:detail', question_id = answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'form':form}
    return render(request, 'board/answer_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    # 질문 삭제
    question = Question.objects.get(id=question_id)
    question.delete()                                               # 해당 질문 삭제
    return redirect('board:boardlist')                                  # 질문 목록

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    # 답변 삭제
    answer = Answer.objects.get(id=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id) # 상세 페이지

templates/board/answer_form.html
{% extends 'base.html' %}
{% block title %}
답변 수정 - Answer
{% endblock %}
{% block content %}
    <div class="container my-3">
        <h1>질문 등록</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <div class="form-group">
                <label for="content">내용</label>
                <textarea id="content" name="content" rows="5" cols="40"
                          class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <input type="submit" value="저장하기" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block title %}
Question - {{ question.subject }}
{% endblock %}
{% block content %}
    <div class="container my-3">
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space:pre-line">{{ question.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if question.modify_date %}       <!-- 수정이 있다면 -->
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ question.author }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                <!-- 질문 수정, 삭제 버튼 -->
                {% if request.user == question.author %}
                <div>
                    <a href="{% url 'board:question_modify' question.id %}" class="btn btn-outline-secondary">수정</a>
                    <a href='#' data-uri = "{% url 'board:question_delete' question.id %}"
                       class="delete btn btn-outline-secondary">삭제</a>
<!--                    <a href="{% url 'board:question_delete' question.id %}"-->
<!--                       onclick="return confirm('정말로 삭제하시겠습니까?')"-->
<!--                       class="btn btn-outline-secondary">삭제</a>-->
                </div>
                {% endif %}
            </div>
        </div>
<!-- 답변 영역 -->
        <h5 class="border-bottom my-3 py-2">
            {{ question.answer_set.count }}개의 답변이 있습니다.
        </h5>
        {% for answer in question.answer_set.all %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space:pre-line">{{ answer.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}       <!-- 수정이 있다면 -->
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ answer.author }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                <!-- 답변 수정, 삭제 버튼 -->
                {% if request.user == answer.author %}
                <div>
                    <a href="{% url 'board:answer_modify' answer.id %}" class="btn btn-outline-secondary">수정</a>
                    <a href='#' data-uri = "{% url 'board:answer_delete' answer.id %}"
                       class="delete btn btn-outline-secondary">삭제</a>
<!--                    <a href="{% url 'board:answer_delete' answer.id %}"-->
<!--                       onclick="return confirm('정말로 삭제하시겠습니까?')"-->
<!--                       class="btn btn-outline-secondary">삭제</a>-->
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <form action="{% url 'board:answer_create' question.id %}" method="post">
            {% csrf_token %}
            {% include 'form_errors.html' %}
<!--            {% if form.errors %}-->
<!--            <div class="alert alert-danger">-->
<!--                {% for field in form %}-->
<!--                    {% if field.errors %}-->
<!--                        <strong>{{ field.label }}</strong>-->
<!--                        {{ field.errors }}-->
<!--                    {% endif %}-->
<!--                {% endfor %}-->
<!--            </div>-->
<!--            {% endif %}-->
            <div class="form-group">
                <textarea name="content" rows="7" cols="60" class="form-control"
                          {% if not user.is_authenticated %} disabled {% endif %}></textarea>
            </div>
            <input type="submit" value="답변 등록" class="btn btn-primary">
        </form>
    </div>
{% endblock %}
      <!--
        <h2>{{ question.subject }}</h2>
        <p>{{ question.content }}</p>
        <h4>{{ question.answer_set.count }}개의 답변이 있습니다.</h4>
        <div>
            <ul>
                {% for answer in question.answer_set.all %}
                <li>{{ answer.content }}</li>
                {% endfor %}
            </ul>
        </div>
        <form action="{% url 'board:answer_create' question.id %}" method="post">
            {% csrf_token %}
            <div>
                <textarea name="content" rows="7" cols="60"></textarea>
            </div>
            <input type="submit" value="답변 등록">
        </form>
        -->
{% block script %}
<script>
    $(document).ready(function(){
        $('.delete').click(function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href=$(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block title %}
Welcome~ PyWeb!!
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
    <h1 class="text-center">어서오세요<br>무엇이든 물어보세요</h1>
    </div>
    <img src="../static/board/css/bg5.jpg" style="width: 100%">
</div>
{% endblock %}

templates/board/question_form.html
{% extends 'base.html' %}
{% block title %}
질문 등록 - Question
{% endblock %}
{% block content %}
    <div class="container my-3">
        <h1>질문 등록</h1>
        <form action="" method="post">
            {% csrf_token %}
    <!--        {{ form.as_p }}-->
            {% if form.errors %}
            {% include 'form_errors.html' %}
<!--
            <div class="alert alert-danger">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
-->
            {% endif %}
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" id="subject" name="subject" class="form-control"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea id="content" name="content" rows="5" cols="40"
                          class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
                <!--textarea 공백 생기지 않게 주의-->
            </div>
            <input type="submit" value="저장하기" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

templates/board/question_list.html
{% extends 'base.html' %}
{% block title %}
질문 / 답변 목록
{% endblock %}
{% block content %}

    <div class="container my-3">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>번호</th><th>제목</th><th>글쓴이</th><th>작성일</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                    {% for question in question_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a>
                    </td>
                    <td>
                        {{ question.author }}
                    </td>
                    <td>
                        {{ question.create_date }}
                    </td>
                </tr>
                    {% endfor %}
                {% else %}
                <p>질문이 없습니다.</p>
                {% endif %}
            </tbody>
        </table>
        <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록</a>
    </div>
{% endblock %}

        <!-- 부트 스트랩 적용 전
        <h1>질문 목록입니다.</h1>
        {% if question_list %}
        <ul>
            {% for question in question_list %}
            <li>
                <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a>        #네임 스페이스 사용
                # <a href="board/{{ question.id }}/">{{ question.subject }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>질문이 없습니다.</p>
        {% endif %}
        <a href="{% url 'board:question_create' %}">질문 등록</a>
        -->